// List of HipChat emoticons to base the collection off of
// https://www.hipchat.com/emoticons
module.exports = [
  '(allthethings)',
  // '(android)',
  '(areyoukiddingme)',
  // '(arrington)',
  // '(arya)',
  // '(ashton)',
  // '(atlassian)',
  '(awthanks)',
  '(awyeah)',
  '(badass)',
  // '(badjokeeel)',
  '(badpokerface)',
  // '(basket)',
  // '(beer)',
  // '(bitbucket)',
  // '(boom)', // #NICETOHAVE - prob make by HipChat
  // '(branch)',
  // '(bumble)',
  // '(bunny)',
  // '(cadbury)',
  // '(cake)',
  // '(candycorn)',
  // '(caruso)',
  // '(ceilingcat)', // #NICETOHAVE - prob violates a copyright
  '(cereal)',
  '(cerealspit)',
  '(challengeaccepted)',
  // '(chewie)',
  // '(chocobunny)',
  // '(chompy)',
  // '(chris)',
  // '(chucknorris)',
  // '(clarence)',
  // '(coffee)',
  // '(confluence)',
  '(content)',
  // '(continue)',
  // '(cornelius)',
  // '(daenerys)',
  // '(dance)',
  '(dealwithit)',
  '(derp)',
  '(disapproval)',
  '(doge)',
  // '(dosequis)',
  // '(drevil)',
  // '(ducreux)', // #NICETOHAVE - prob violates a copyright
  '(dumb)',
  '(facepalm)',
  // '(failed)',
  '(firstworldproblem)',
  // '(fonzie)',
  '(foreveralone)',
  '(freddie)',
  // '(fry)', // #NICETOHAVE - violates a copyright
  '(fu)',
  '(fuckyeah)',
  // '(fwp)', // #DUPLICATE of (firstworldproblem)
  // '(gangnamstyle)',
  // '(garret)',
  // '(gates)',
  // '(ghost)',
  // '(goodnews)', // #NICETOHAVE - violates a copyright
  // '(greenbeer)',
  // '(grumpycat)', // #NICETOHAVE - prob violates a copyright
  '(gtfo)',
  // '(haveaseat)',
  // '(heart)',
  // '(hipchat)',
  // '(hipster)',
  // '(hodor)',
  '(huh)',
  '(ilied)',
  '(indeed)',
  '(iseewhatyoudidthere)',
  // '(itsatrap)', // #NICETOHAVE - violates a copyright
  '(jackie)',
  // '(jaime)',
  // '(jira)',
  // '(jobs)',
  // '(joffrey)',
  // '(jonsnow)',
  // '(kennypowers)',
  // '(krang)',
  // '(kwanzaa)',
  // '(lincoln)',
  '(lol)',
  // '(lolwut)',
  '(megusta)',
  // '(menorah)',
  '(mindblown)',
  // '(ned)',
  // '(nextgendev)',
  // '(ninja)',
  '(notbad)',
  '(nothingtodohere)',
  // '(notsureif)', // #DUPLICATE of (fry)
  '(notsureifgusta)',
  // '(obama)',
  '(ohcrap)',
  '(ohgodwhy)',
  '(okay)',
  '(omg)',
  '(orly)',
  // '(pbr)',
  // '(pete)',
  '(philosoraptor)',
  // '(pingpong)',
  // '(pirate)',
  '(pokerface)',
  // '(poo)',
  // '(present)',
  // '(pumpkin)',
  '(rageguy)',
  // '(rebeccablack)',
  // '(reddit)',
  // '(romney)',
  // '(rudolph)',
  // '(sadpanda)',
  '(sadtroll)',
  // '(samuel)',
  // '(santa)',
  // '(scumbag)',
  // '(seomoz)',
  // '(shamrock)',
  '(shrug)',
  // '(skyrim)',
  '(stare)',
  // '(stash)',
  '(success)',
  // '(successful)',
  '(sweetjesus)',
  '(tableflip)',
  // '(taft)',
  // '(tea)',
  // '(tree)',
  '(troll)',
  '(truestory)',
  // '(trump)',
  // '(turkey)',
  // '(twss)',
  // '(tyrion)',
  // '(tywin)',
  // '(unknown)',
  // '(washington)',
  '(wat)',
  // '(whynotboth)',
  '(wtf)',
  '(yey)',
  '(yodawg)',
  // '(yougotitdude)',
  '(yuno)',
  // '(zoidberg)',
  // '(zzz)',
];
