// List of emoticons to URL mappings
// DEV: List reduced from HipChat's set of emoticons
// DEV: https://www.hipchat.com/emoticons
module.exports = {
  '(allthethings)': 'http://cdn.alltheragefaces.com/img/faces/png/misc-all-the-things.png',
  // '(android)': '',
  '(areyoukiddingme)': 'http://cdn.alltheragefaces.com/img/faces/png/misc-are-you-fucking-kidding-me-clean.png',
  // '(arrington)': '',
  // '(arya)': '',
  // '(ashton)': '',
  // '(atlassian)': '',
  '(awthanks)': '',
  '(awyeah)': '',
  '(badass)': 'http://cdn.alltheragefaces.com/img/faces/png/misc-got-a-badass-over-here.png',
  // '(badjokeeel)': '',
  '(badpokerface)': '',
  // '(basket)': '',
  // '(beer)': '',
  // '(bitbucket)': '',
  // '(boom)': '', // #NICETOHAVE - prob make by HipChat
  // '(branch)': '',
  // '(bumble)': '',
  // '(bunny)': '',
  // '(cadbury)': '',
  // '(cake)': '',
  // '(candycorn)': '',
  // '(caruso)': '',
  // '(ceilingcat)': '', // #NICETOHAVE - prob violates a copyright
  '(cereal)': 'http://cdn.alltheragefaces.com/img/faces/png/cereal-guy-cereal-guy-original.png',
  '(cerealspit)': 'http://cdn.alltheragefaces.com/img/faces/png/cereal-guy-cereal-guy-spitting.png',
  // TODO: Trim remove CHALLENGE ACCEPTED text
  '(challengeaccepted)': 'http://cdn.alltheragefaces.com/img/faces/png/determined-challenge-accepted.png',
  // '(chewie)': '',
  // '(chocobunny)': '',
  // '(chompy)': '',
  // '(chris)': '',
  // '(chucknorris)': '',
  // '(clarence)': '',
  // '(coffee)': '',
  // '(confluence)': '',
  '(content)': 'http://cdn.alltheragefaces.com/img/faces/png/happy-kitteh-smile.png',
  // '(continue)': '',
  // '(cornelius)': '',
  // '(daenerys)': '',
  // '(dance)': '',
  '(dealwithit)': '',
  '(derp)': '',
  '(disapproval)': '',
  '(doge)': '',
  // '(dosequis)': '',
  // '(drevil)': '',
  // '(ducreux)': '', // #NICETOHAVE - prob violates a copyright
  '(dumb)': '',
  // '(facepalm)': '', // #CUT
  // '(failed)': '',
  // '(firstworldproblem)': '', // #CUT
  // '(fonzie)': '',
  '(foreveralone)': '',
  '(freddie)': '',
  // '(fry)': '', // #NICETOHAVE - violates a copyright
  '(fu)': '',
  '(fuckyeah)': 'http://cdn.alltheragefaces.com/img/faces/png/fuck-yeah-clean.png',
  // '(fwp)': '', // #DUPLICATE of (firstworldproblem)
  // '(gangnamstyle)': '',
  // '(garret)': '',
  // '(gates)': '',
  // '(ghost)': '',
  // '(goodnews)': '', // #NICETOHAVE - violates a copyright
  // '(greenbeer)': '',
  // '(grumpycat)': '', // #NICETOHAVE - prob violates a copyright
  '(gtfo)': '',
  // '(haveaseat)': '',
  // '(heart)': '',
  // '(hipchat)': '',
  // '(hipster)': '',
  // '(hodor)': '',
  // '(huh)': '', // #DUPLICATE of (gtfo)
  // '(ilied)': '', // #CUT I don't think everyone understands this one
  '(indeed)': 'http://cdn.alltheragefaces.com/img/faces/png/neutral-feel-like-a-sir-clean.png',
  '(iseewhatyoudidthere)': '',
  // '(itsatrap)': '', // #NICETOHAVE - violates a copyright
  // '(jackie)': '', // #CUT
  // '(jaime)': '',
  // '(jira)': '',
  // '(jobs)': '',
  // '(joffrey)': '',
  // '(jonsnow)': '',
  // '(kennypowers)': '',
  // '(krang)': '',
  // '(kwanzaa)': '',
  // '(lincoln)': '',
  '(lol)': '',
  // '(lolwut)': '',
  '(megusta)': '',
  // '(menorah)': '',
  // '(mindblown)': '', // #NICETOHAVE - prob violates a copyright
  // '(ned)': '',
  // '(nextgendev)': '',
  // '(ninja)': '',
  '(notbad)': '',
  '(nothingtodohere)': '',
  // '(notsureif)': '', // #DUPLICATE of (fry)
  '(notsureifgusta)': '',
  // '(obama)': '',
  '(ohcrap)': '',
  '(ohgodwhy)': '',
  '(okay)': '',
  '(omg)': '',
  // '(orly)': '', // #CUT
  // '(pbr)': '',
  // '(pete)': '',
  // '(philosoraptor)': '', // #CUT
  // '(pingpong)': '',
  // '(pirate)': '',
  '(pokerface)': 'http://cdn.alltheragefaces.com/img/faces/png/neutral-poker-face-clean.png',
  // '(poo)': '',
  // '(present)': '',
  // '(pumpkin)': '',
  // '(rageguy)': '', // #DUPLICATE of (fu)
  // '(rebeccablack)': '',
  // '(reddit)': '',
  // '(romney)': '',
  // '(rudolph)': '',
  // '(sadpanda)': '',
  // '(sadtroll)': '', // #CUT
  // '(samuel)': '',
  // '(santa)': '',
  // '(scumbag)': '',
  // '(seomoz)': '',
  // '(shamrock)': '',
  // '(shrug)': '', // #CUT
  // '(skyrim)': '',
  '(stare)': '',
  // '(stash)': '',
  '(success)': '',
  // '(successful)': '',
  '(sweetjesus)': 'http://cdn.alltheragefaces.com/img/faces/png/sweet-jesus.png',
  // '(tableflip)': '', // #CUT
  // '(taft)': '',
  // '(tea)': '',
  // '(tree)': '',
  '(troll)': 'http://cdn.alltheragefaces.com/img/faces/png/troll-troll-face.png',
  '(truestory)': '',
  // '(trump)': '',
  // '(turkey)': '',
  // '(twss)': '',
  // '(tyrion)': '',
  // '(tywin)': '',
  // '(unknown)': '',
  // '(washington)': '',
  '(wat)': '',
  // '(whynotboth)': '',
  // '(wtf)': '', // #DUPLICATE of (dumb)
  '(yey)': '',
  // '(yodawg)': '', // #CUT
  // '(yougotitdude)': '',
  '(yuno)': '',
  // '(zoidberg)': '',
  // '(zzz)': '',
};
